site_projects:
    resource: "@SiteProjectsBundle/Controller"
    type:     annotation  

site_accueil:
    resource: "@SiteAccueilBundle/Controller"
    type:     annotation  

site_contact:
    resource: "@SiteContactBundle/Controller/"
    type:     annotation
