services:
    contact.menu_builder:
        class: Site\ContactBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    contact.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: contact.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: contact } # L'alias est très important, c'est avec lui que vous appellerez votre menu dans la vue